### ISSUE TITLE
What's Next?

### ISSUE THREAD

**Issue by theo-armour** [fgx/fgx.github.io#22]
@fgx/owners 

I'm seem to be finishing  up another project I've been working on. Will send link when it's ready - it kind of relates to FGx.

When I do finish, what should I work on next? Any thoughts?

Also, how is work on the FGx launcher progressing? If anything is happening should I think about updating http://fgx.github.io/?

**Comment by geoffmcl** [comment]
Hi Theo,

I have nothing very specific in mind, but extending the current flightpath
3D display...

This is a known path, loaded, but what about a live json/xml flight?

I will get around to flying some more circuits, and build up some more
pre-loaded cvs/kml paths... I thought of VHSK... a 500 foot circuit there
is well below lots of the terrain, and should be spectacular... and
familiar to us both... maybe you can suggest somewhere where the terrain
itself is spectacular...

But what about a live flight, at the same terrain level as flightpath...
initially with no model, and just looking forward, in the direction of the
flight...

I think the current model is a tad too big, but you mentioned something
about this model... I think it should be reduce by a factor of 2, if not
more, to fit more realistically within the scene...

You have to find the flight - given a callsign=ABCD - in the current
crossfeed list, to even get the first world coordinates, before you can
even think about adding the terrain...

But the aircraft can be plotted exactly as it progresses... of course
pretty boring if at 32,000 feet over water... but VFR, and low level
flights, here meaning below some of the terrain...

And if it flies off the current terrain tile, then the next must be
scheduled... I think the previous, I think 512x512 mess was fine, 2X did
not look greatly better, and did not like the extra google ad line...

So maybe a **FG Live 3D Tracker**... would be fantastic...

Concerning FGx launcher, now FGFS includes a built in Qt 5 GUI launcher.
which I have yet to explore, but from what I have read, mostly replaces
what FGx provided, so it is quite low in my TODO list...

It had some nice selections, with maps, etc, which I am sure the built-in
will not have... but maybe less, no need now?

Anyway, looking forward to more 3D events from you...

Regards,

Geoff.

**Comment by theo-armour** [comment]
@geoffmcl 

Added to the [Flightpath2 To Do list](http://fgx.github.io/sandbox/flightpath2/index.html#readme.md)

## To Do List
-  Live flight, at the same terrain level as flightpath...
- > Current model is a tad too big < add a slider that scales the model
- Plotting Crossfeed flights. **FG Live 3D Tracker**
