### ISSUE TITLE
2016-07-17 ~ KGCN FlightPath R1

### ISSUE THREAD

**Issue by theo-armour** [fgx/fgx.github.io#31]
![image](https://cloud.githubusercontent.com/assets/547626/16904364/4b5b0edc-4c49-11e6-8586-562ec420c7a6.png)

@fgx/owners 
### 2016-07-17 ~ R1
- Terrain only for today
- First commit
- Add Read Me

**Comment by theo-armour** [comment]
![image](https://cloud.githubusercontent.com/assets/547626/16932392/f0de8b66-4cfa-11e6-87f3-2982a3d46986.png)

@fgx/owners

Ignore position discrepancies for the moment. WIP. 

## [ VHSK FlightPath R1.1 ](http://fgx.github.io/sandbox/flightpaths/vhsk/)

### Change Log 2016-07-18 ~ R1.1
- Read flight path data
- Draw 3D line and bounding box
- Major code streamline

**Comment by pedromorgan** [comment]
Where is SID and more important STAR

**Comment by theo-armour** [comment]
They are scheduled for delivery in the near future.

The flying spaghetti monster will appear on your screen soon!

**Comment by pedromorgan** [comment]
U need to get a bit "git" but mr Paris also dont realise powers of www and
data set..

So get a life betweren geoff+Theo....
create one JS.lib.. and make one version only in JS and all.

Otherwise its all fundamentally flawed..

**Comment by theo-armour** [comment]
@pedromorgan 

> > Otherwise its all fundamentally flawed..

Can you supply a link to somebody who does it better?

**Comment by theo-armour** [comment]
## [ VHSK FlightPath R1.2 ](http://fgx.github.io/sandbox/flightpaths/vhsk/)

### 2016-07-19

Flight path lat & lon now seems to register properly with ground lest lat & lon
- Ground mesh now sized according to deltaLat x deltaLat

**Comment by paulmasson** [comment]
Flying spaghetti monster???

**Comment by geoffmcl** [comment]
@paulmasson yes, an interesting **description** ;=))

My understanding, and I am sure Theo will correct me if I am wrong... he coined the phrase... but...

When you add a display of SID/STAR way-points, tracks, you get a `spaghetti` like display... e.g. [map-fsm](http://geoffair.org/fg/map-test2/map-fsm.html) -- `fsm` === `flat spaghetti monster` ;=))

Of course, Theo wants to show that in 3D... maybe as `tubes`... maybe he has a sample, but have forgotten where exactly...

Making `sense` of this depends a lot on what you are trying to display, and from what SID/STAR source information you have, or can find, for each airport in the world... lots of info...

Viva le/la(?) `FSM` ;=)) may it return soon to a screen near you... 

Anything you can do to help this, it would be much appreciated... thanks...

**Comment by theo-armour** [comment]
@paulmasson @geoffmcl 

FSM  code: all links to the 'dev' version of Three.js - and much is broken because of this. 

Must go back and link these adds to their contemporary versions.

**Comment by theo-armour** [comment]
![image](https://cloud.githubusercontent.com/assets/547626/17004478/038b6cf8-4e8a-11e6-9a3b-663091105ad2.png)

@fgx/owners 

Another well-positioned flight.

Thanks to Geoff for the paths are in feet heads-up!

http://fgx.github.io/sandbox/flightpaths/kgcn/kgcn-flightpath-r2.html
