### ISSUE TITLE
Use of issues, and tag, releases

### ISSUE THREAD

**Issue by geoffmcl** [fgx/fgx.github.io#4]
@theo-armour, wow, what an interesting use of `issues` ;=))

So what are you doing... each improvement, addition, change, ... the final html is a **new** issue?

And with that **new** version, a **new** 2D image added... lots to follow...

No problem... so this is an issue, **what is an issue here**?

Outstanding issues, that I see -
- `real` data - delayed, waiting cfm of circuit to use... can not guess this...
- transform that data, where each wpt is dist from last, to set **exact** speed of model...
- default mode, the model does some **odd** twists on turns, maybe need roll change...
- `Camera Follow` mode is close to **perfect** ;=)) thanks for R5...
- `Camera angle` should be 360 degrees, going around the ac
- `Camera World` seems to be a wing-man, holding off to the left, hmmmm?
- If `Camera World` is a true wing-man, the camera switches to his/her view.
- add 3D DEM terrain - getting sick of green squares...
- add 3D POI, in this case, like castle, and freeway intersection, visual turn clues
- and **more** to make this a **real** sim PPL circuit view...

If you add a tag, like `$ git tag R5`, and `$ git push --tags`, that forever records that moment in git history, and allow a git users to, at any time, recover that version... review it... set up to run it... etc...

So my idea, in git at least, is that there is absolutely no necessity to create a **new** html file name, folders, for the latest... just roll on modifying the last... and push, maybe add comment...

But that is all stupid **style**... I also have no problem with a **new** link that points to new `R???`, or a link to point to that...

This has progressed **massively**... thanks Theo for your web 3D perspective...

If you want to view the `real thing`, then found this video, [Tecnam P96](https://www.youtube.com/watch?v=f93h_sjzJXA). Is a runway 35, left, 500 foot circuit, and shows the importance of visual, on ground, clues, and all-around-vision... note frequent left-right quick looks, for orientation..

Onwards, to the better... ;=)) in what ever `forum` style...

**Comment by theo-armour** [comment]
@geoffmcl 

## Misunderstanding

From reading your message:

I believe, you think you are waiting for me for data. But I know that I am waiting for you for data. ;-)

Can we try to get to a mutual understanding?

You would like to recreate flying lesson flight paths - going around circuits and doing touch and go landings and so on.

There are a number of methods to create these flight paths
1. Generating points by algorithm
2. Generating points by trial and error - as I have been doing up to now
3. Gathering points generated by by FlightGear sessions

Using #2 sucks and - because of gimbal lock issues because the use of splines to interpolate looks bad.

Using #1 would take a long time because airplane movement heuristics ain't easy stuff.

#3 on the other hand seems doable. If you can record flight data ( lat, lon, alt - or whatever you want ) from any point A to any point B then I can build the flight path.

If you supply the data, I will use the data to create the simulation. Any latitudes & longitudes you want. At any time interval you want. 5hz is OK.

And, the nice thing, given you lats and lons I can start to add geography.

 But without good flight path data then there will be jerky, sucky movements and so on.

A flight of a few minutes will do. CSV is nice, but I'll take KML if I have tpo

Now, in you message you raise a lot of other interesting points. We will get to these.

But in the absence of a good sample flight path data file from you we won't go far.

Am I being clear? 

Probably not. ;-) But let's keep trying to reach an understanding.

Theo

**Comment by geoffmcl** [comment]
@theo-armour this is item 1 from my list

```
1: real data - delayed, waiting cfm of circuit to use... can not guess this...
```

I decided not to wait for local flight instructor approval of this as a circuit, but it would certainly pass as a short cross-country VFR flight...

The README-LEIG.md contains some more details of what I add, how generated, etc... but I think for you the main file is **LEIG-L1500-cooked-01.csv**...

Can not immediately see how to attach my png... out of time tonight, but will try a drag-and-drop later... 

Hope this is one step up the ladder ;=))

**Comment by theo-armour** [comment]
@geoffmcl 
We should be flying real soon now,

BTW, you can drag and drop images into GitHub issues online pages

**Comment by geoffmcl** [comment]
@theo-armour trying the drag-and-drop, but work so much in the command prompt these days, often **forget** these GUI to browser GUI **easy** transfers...

So next should be the **desired** 2D xg, informational view...

![leig-l1500-01](https://cloud.githubusercontent.com/assets/1333435/14657808/19c32bce-0690-11e6-9f91-4ad68ff1123c.png)

Yeah, what a simple way to add an image ;=))

It seems it uploaded the png to a github cloud user content, addressed by a, I suppose, a sha1 reference... cool... if you can afford the web space... which I hope is added to our github usage stats... always **thank you** to GitHub for these great **free** assets...

But the point is, remember, these are **only** desired, suggested, POI displays, placards, ... and would seek web ways to implement them for each **new** airport added...

The next idea is [VHSK](https://en.wikipedia.org/wiki/Shek_Kong_Airfield), where I flew a RL 500 ft, left, circuits, so many times, for my PPL, in a c152, and before that, parachuted from a c182, so the c172p can do the same circuit very easy...

Again because of the mountain right in front, [Tai Mo Shan](https://en.wikipedia.org/wiki/Tai_Mo_Shan), ... 3,000 ft plus... must smartly turn left on establishing climb...

Again, with 3D terrain, this could **look** spectacular... but still to be done... fly it... collect `raw`... run script to produce `cooked`.... publish...

Looking forward to an **update** for LEIG ;=))

**Comment by theo-armour** [comment]
Your data is good. See my status update. Yay, and thanks!

Sorry, I misunderstood that you were waiting for some outside event ( cfm??? ) to happen.

> > Yeah, what a simple way to add an image ;=))

Yup, and you can do a screen grab and then Control-V as well.

> >  if you can afford the web space... which I hope is added to our github usage stats

1 GB+ per repo. And as many repos as you want. Disk space is no longer an issue.

> > If you add a tag, like $ git tag R5, and $ git push --tags, that forever records that moment in git history, and allow a git users to, at any time, recover that version... review it... set up to run it... etc...
> > So my idea, in git at least, is that there is absolutely no necessity to create a new html file name, folders, for the latest... just roll on modifying the last... and push, maybe add comment...

Programmers look at code so git tags work. On the other hand, designers look at the web pages/apps.

Find me a quick way to create links to view the web pages / the output of multiple revisions - to be able to compare and contrast visual output - and I'm on board.

> > But the point is, remember, these are only desired, suggested, POI displays, placards

Added to Road Map

**Comment by geoffmcl** [comment]
@theo-armour see #5 for some small updates... basically wanted to check the flight in Google Earth without going to all the trouble of re-flying the circuit with FG Multiplayer **ON**, so I could download the FG Tracker XML, so...

So wrote an xg2xml.pl script, to read the **cooked** and generate an suitable XML... that worked... and added a png image as scraped from **GE**...

The main thing about the POI/Placards is you need to advise a way how to include these...

The new 3D flight, #5 R6, looks **great** ... thanks...

**Comment by theo-armour** [comment]
> > The main thing about the POI/Placards is you need to advise a way how to include these...

Can you attach the flight POIs as an extra field to the CSV files?

That way they can be displayed as and when they are relevant.

Location stuff - such as castles etc - could either be is a separate CSV file with notes + lat/lon. Or we could use the Google Maps API to point things out.

Let me know if this is OK. If so we can close this issue...

**Comment by geoffmcl** [comment]
Hi Theo,

It's tough keeping these `threads` together, over about the same thing, but this is about **adding** POIs/pacrards to your html display...

I asked:

> The main thing about the POI/Placards is you need to advise a way how to include these...

You replied:

> Can you attach the flight POIs as an extra field to the CSV files?

Describe that to me... I do **not** understand!

To me a CSV file is exactly that, a set of comma separated values... usually a csv file commences with a `header` line giving `titles` to the array...

How can a POI, like say the **castle** be added?

If you can bear with me for a moment, that `castle` can be simply described by this xg (xgraph) file - in 3D terms, the lack of an `altitude` simply means the brown polygon mesh needs to be laid on the terrain, and a placard "Castle ... on hill" added -

```
color brown
anno 1.66967652 41.55539495 Castell de Cabrera, on hill
1.66849425 41.55497105
1.66932909 41.55462301
1.67033873 41.55556423
1.66995789 41.55600767
# close polygon == first point
1.66849425 41.55497105
NEXT
```

Yes, we could use "Google Maps API to point things out.", but that has its big problems... like how to `name` the POI that exists in GM, and what is it going to display? Many questions... seems too out-of-control...

This also has to be `generic`... next week, month I want to feature a **new** airport circuit... remember this is about PPL student touch-and-go circuit training... **not** a general POI travel log of the region...

So I want a way to describe the `features` that **need** to be exposed for this **specific** purpose...

Ok, it seems your #7 and #8 are exploring the Google API... that is fine... that is **great**... but to me, a little off track... but, hey, everything is worth exploring? it is fun... right?

Theo, I would really prefer a `thread` where we can discuss this, instead of bouncing issue to issue... sort of as you have new idea... 

But, as always, will keep trying to follow ;=))

This is sort of also in reply to #6 - 2D GE,  #7 - GDEM service, and #8 - GDEM display...

To me this issue #4 is still a question! Like how to follow this and make sense? So, **no** I do **not** think this issue, namely `Use of issues,...` is **closed**!

**Comment by theo-armour** [comment]
@geoffmcl 

## Points of Interest

It seems to me that are different types of 'points of Interest'
1. There those that you insert as comments - as mentioned in your message of 15 April

> Ignore the # comment lines, of course... this is -
> lat,lon,alt,speed
> 
> ;# on runway, speed 40 kts
> ;# anno 41.58841468,1.65458904 Runway 17 0 40
> 41.58841468,1.65458904,0.40
> ;# anno 41.58841468,1.65079197 Runway 17 250 80
> 41.58841468,1.65079197,250,80
> ;# anno 41.5429563588446 1.67387784448875 ____ R-TR 500 100
> 41.5429563588446,1.67387784448875,500,100 
> ;# anno 1.69565406162373 41.5491956155896 cross
> ;# anno 1.71743446547134 41.5554307410213 R-TL
> 41.5554307410213,1.71743446547134,500,100 
> ;# anno 1.69627651400159 41.5971530558658 downwind
> '# anno 1.67509129317349 41.6388711688456 R-BL
> 41.6388711688456,1.67509129317349,500,80 
> '# anno 1.65328281246059 41.6326361523603 base
> ;# anno 1.63147853558338 41.6263969925269 ____ R-BR
> 41.6263969925269,1.63147853558338,250,80
> ;# anno 1.64303784239271 41.6036701971992 final 17
> ;# 1.67387784448875 41.5429563588446
> 41.58841468,1.65079197,0,40
1. There are those that air controller waypoints

I believe you supplied a bunch of these here

https://github.com/fgx/fgx-airports/blob/gh-pages/csv-data/xp-awy.csv

But without polyline data
1. And there are points of interest that are buildings, highways and other man-made stuff

---

It's type #1 that I thought could be added to the flight path CSV

Type#2 could be in a separate file to be read at load time

Type #3 is a nice can of worms that we can work on after taking care of #1 and #2 

---

And, yes, please do open a POI thread so we can have an ongoing discussion on this particular topic - quite separate from particular script status updates

**Comment by theo-armour** [comment]
@geoffmcl 

Anything else here to go over?
