### ISSUE TITLE
2016-08-05 ~ FGx Crossfeed Dailies Replay R6

### ISSUE THREAD

**Issue by theo-armour** [fgx/fgx.github.io#40]
@fgx/owners

It still takes my breath away that a 30+ Mb CSV file can be downloaded and parsed, a 700 Kb bitmap downloaded, parsed and turned into a 2048 x 1024 3D mesh, and some dozens of aircraft path created in a matter of a few seconds.

Most of the problem is trying to convince your brain that loading time is not an issue any more.
## Change Log ~  2016-08-05 ~ R6
- No more zombies just about
- Needs to indicate where callsigns are warp speeding instead of flying
- Needs to indicate which callsigns are not currently flying

**Comment by pedromorgan** [comment]
![theo-3d](https://cloud.githubusercontent.com/assets/123932/17453892/54abeaa4-5b7d-11e6-83d6-72d8d5ecb03e.jpeg)

**Comment by pedromorgan** [comment]
Looks well strange to me..

We need to get down into nitty gritty..
Like making side bar work on mobiles and all sort of json stuff..

Looks like a lot of stones and ideas are being tested and works kinda..
But what we all want is a cool live tracking/replay sstem for atc, maps airports et all..

Need to kick up fg-navdb again, and into spatial postgis..
This way u can send position and get airports in bbbox et all, distances etc
https://github.com/freeflightsim/fg-navdb

**Comment by theo-armour** [comment]
@pedromorgan 

> Like making side bar work on mobiles and all sort of json stuff..

My bad. Thanks for catching. The 'hamburger' icon you see in your desktop screen shot,  disappears on my Android - which is where it's needed.  Will fix.

This 'replay' globe is still at a very early stage of life.

> But what we all want is a cool live tracking/replay sstem for atc, maps airports et all..

The globe live tracker - as it has been since 2013 - is here:

http://fgx.github.io/fgx-globe/

The airport/ILS tracker is here:

http://jaanga.github.io/fgx-plane-spotter/r4/fgx-plane-spotter-r4.html

These last two are way out of date now, but still fun to look at.

**Comment by theo-armour** [comment]
> > We need to get down into nitty gritty..
> > Like making side bar work on mobiles and all sort of json stuff..

http://fgx.github.io/sandbox/globe-crossfeed-replay/globe-crossfeed-replay-r6.html

Yesterday, using this link I opened the script and the slide 'hamburger' icon was a no-show.

Today, I cannot reproduce this issue. The icon always appears. ;-(

If you can find a way of repeating the no-show icon, I would appreciate this.

---

Where, I do see a problem is with the sandbox menu:

http://fgx.github.io/sandbox/

It sucks on a mobile phone in portrait mode. This will definitely be fixed soon!

The goal, of course, would be a menu that slides when you slide your finger. But this would have to be on the menu only. Because in the 3D world sliding your finger is used to rotate the camera.

**Comment by pedromorgan** [comment]
Have u looked at bootstrap as an interface design..

Kinda does all we need,
http://getbootstrap.com/

And dead easy to style etc

**Comment by pedromorgan** [comment]
oops meant as an "interface frameowork"..

**Comment by theo-armour** [comment]
@pedromorgan 

> Have u looked at bootstrap as an interface design..

Yes, If I were to use a 2D library it probably would be Bootstrap - at least to start with.

The first thing is that 90% of what I work on is 3D and WebGL. None of the standard web page libraries are of any use at all with WebGL. 

The second thing is that I write cookbook code - or cut and paste code as you call it. 

One of the rules of cookbook code is that you don't mix libraries. One example, one library.  

So my 2D HTML stuff is just pure JavaScript. And, I'm happy with this as it makes explore even more what's doable with JavaScript

But if somebody does want to build a fancy 2D front end, then I am happy tp slip down into an iframe and throw data back and forth over the wall.

**Comment by pedromorgan** [comment]
Main idea is we have template and 
- top navigations
- and standard libe on cdn
- and off u go on code...

Mr doobs idea is cool, but in a running www site.. we need the "fremework" and context and stuff..

So our idea  if templating is moot, and u are on your own when it comes to "mobile firendllye"

Instead we use Boostrap and a template nad three js instead..
and everything is there.. all u have to do is create the content..

Whatever that is..

**Comment by theo-armour** [comment]
@pedromorgan 

> Main idea is we have template and

I adore templates (and snippets)

Here's links to two menus of templates I use:
- http://jaanga.github.io/cookbook-html/templates/
- http://jaanga.github.io/cookbook-html/examples/github-api-rss/github-api-files-viewer/

Of course. it's always out of date.  ;-)

The issue is that there are not a lot of templates for 3D content. Things are moving quite fast in 3D. The Three.js library is now on R80. Each rev has adds a good number of new features. Sometimes your enemy is yesterday's template. This does not seem to stop me from creating them.

> top navigations

I don't understand what this means.
- and standard libe on cdn

Three.js is available via a number of CDN including csnjs and npm. The issue is that necessary plugins are not. So generally I use these links

<script src=http://rawgit.com/mrdoob/three.js/dev/build/three.min.js ></script>

<script src=http://rawgit.com/mrdoob/three.js/dev/examples/js/controls/OrbitControls.js ></script>

<script src=http://rawgit.com/mrdoob/three.js/dev/examples/js/libs/stats.min.js ></script>

The good thing is that the code is always based on latest version of Three.js.

> Mr doobs idea is cool, but in a running www site.. we need the "fremework" and context and stuff..

What we are talking about here has little to do with Mr.doob. 

Mr.doob maintains the most popular library in the world for playing with 3D in a canvas tag using WebGL, but he says little or nothing about building web sites.

> all u have to do is create the content..

That's the interesting thing with 3D. There's almost no content. It's all code. Or the content is coded

Have a look at this sample:

http://mrdoob.com/projects/htmleditor/

How would you improve this demo with Bootstrap?

And look at these examples

http://threejs.org/examples/#webgl_geometry_nurbs

What would Bootstrap do to help code any of these examples faster?

I am not saying they cannot be frameworked. All I am saying is that I am not enough of a programmer to see how to do it.

> So our idea if templating is moot, and u are on your own when it comes to "mobile firendllye"

Being mobile-friendly is a really high priority item for our efforts.

Creating 3D worlds on your phone has a lot of issues, but it can be done.

For example: what issues do you have with fgx.github.io/fgx-globe/?

The issues I have is that:
- the menu slide-in 'hamburger' icon is not easy to spot
- it does not automatically update on a screen rotate.

Yes, there are probably a bunch of iOS issues, but apart from that,
do you have any thoughts as to what could make it a better mobile app?

PS if you are an iOS user, then I will add a build branch with the fixes for non-compliance that  iOS needs instead of sending out my dev branch.

**Comment by pedromorgan** [comment]
I think we are at cross purposed re templates..

The template idea is that the main headers, js, css etc inc basic page is on the server..
a "content template" is then sat in the middle with the application..

This makes it dead eas to update all threejs in one go etc... etc

It still ends up being a html page.. but assembled upon server..

This had other benifits also such as caching, compressing js files, html et etc..

All i need is time..

pete

**Comment by theo-armour** [comment]
@pedromorgan 

Lots of good points. I'm enjoying the discussion.

> This makes it dead eas to update all threejs in one go etc... etc

The three or. four or so Three.js library files I use are always called from the GitHub CDN - rawgit.com. And the dev branch is always called. So you always get they latest build automatically and I have to do nothing. Very occasionally a build will add something that breaks everything and I jave to do a mad dash to fix things. But that has been quite a rare event.

With very old scripts, I sometimes reset them to call for the latest build that still works.

> This had other benifits also such as caching, compressing js files, html et etc..

The Three.js files are already minified. And I find that Rawgit takes care of the caching globally fairly well.

> It still ends up being a html page.. but assembled upon server..

For the past few years I've been using GitHub pages as a server. It's a static file server only. So it's not possible to assemble files there.

Much of my code is intended to help beginners. In other words, peeps with no servers. So GitHub has been OK and I encourage beginners to get accounts.

Also the delivery has been fairly good.  For example, I thought it would be necessary to read Geoff's daily Crossfeed files in 1MB chunks because they are over 30MB each. But no need. They seem to load in seconds.

I'm very willing to try new things.

So, for example, would it be possible to set up something so my files would be copied from GitHub to freeFlightSim once a day?
