### ISSUE TITLE
Move to freeFlightSim?

### ISSUE THREAD

**Issue by theo-armour** [fgx/fgx.github.io#41]
@fgx/owners 

Two Questions:
1. Should I create a GitHub Pages freeflightsim.github.io repo and copy the relevant FGx files over to there - and then continue my current efforts there?
2. Can we use the FGx pilots cap logo over there as well?

**Comment by geoffmcl** [comment]
As indicated elsewhere, do **not** see the reason for this!

Replacing typing 3 letters, with 13! more typing, more initial setup... for what gain?

To quote the Bard -

```
What's in a name? that which we call a rose
By any other name would smell as sweet;
```

I like the smell of `FlightGear eXtra` - FGx... short and sweet...

Regards,
Geoff.

**Comment by pedromorgan** [comment]
err ok we stick to FGx..

And to remind geoff
the `x` in `fgx` was Gral making on osx dist and launcher.. still a pin to this day...
so fgx. was from gral and I created also same time launcher..ffs
so I removed xml stuff
and create in c++ pure
and then geoff came in and off we went..

BTW geoff.. The fgx+5 is there as branch.. but do we bother ?
seems like qt5 is now in the "chain" and much hate removed etc etc..

So ther is still no official "osx release".. and all other stuff

pete

**Comment by pedromorgan** [comment]
OSx is the x in Fg.x

**Comment by theo-armour** [comment]
Is it OK if we change the 'is' to 'was'?

**Comment by theo-armour** [comment]
@geoffmcl 

I'm enclosing this issue, out it's OK.

Look at the traffic here: it's dead:

https://github.com/fgx/fgx.github.io/graphs/traffic

While I'm still alive, working on dead sites is no pleasure.

It would be a good thing to attract some traffic.

If you say 'fgx' to peeps they say: huh?

If you say 'free flight sim' they say: 'cool'

Another aspect is that it's a good thing if the server and GitHub repos have similar names.

Since Pete is offering freeflightsim.org, it might help with traffic if the GitHub repos also use the same name.

Certainly, FGx has history and it's a short tidy name. If you have some ways of bringing in traffic to FGx, then do shout!
