### ISSUE TITLE
Update ~ 2016-04-20 ~ Flight Path to 2D Map Texture

### ISSUE THREAD

**Issue by theo-armour** [fgx/fgx.github.io#6]
![image](https://cloud.githubusercontent.com/assets/547626/14698448/bc81a044-0743-11e6-859e-a402ed576c4f.png)

---

@fgx/owners 

This is one of several side trajectories needed to complete FGx FlightPath.

The interesting thing is that the Google Map APIs have been upgraded since we last had a look. Now a lot less work has to be done in order to display the desired map. Therefore it has taken quite a bit of work to figure out how much less work needs to be done. 

There's another side trajectory today that was carried out over at Jaanga. The work product from that effort seems to be progressing well. With a bit of luck, that effort will come over here nicely and FGx will have some nice new 3D terrain capabilities.

The Jaanga effort is about capturing significant amounts of 3D elevation data from the Google Elevation API in near real time and being able to use that data to display 3D terrains. This would be a significant change from earlier efforts that are about creating static repositories on GitHub full of bitmaps.

---
### Features
- Given minimum and maximum latitude and longitude
  - Requests, receives. load and displays appropriate Google map
  - Draws polyline indicating latitudes and longitudes
  - Applies combined image to Three.js plane buffere geometry
### 2016-04-20
- [Flight Path to 2D Map Texture R1](http://fgx.github.io/sandbox/flightpath-to-2d-map-texture/flightpath-to-2d-map-texture-r1.html)

**Comment by geoffmcl** [comment]
@theo-armour yes, I can see maybe the terrain could come from the Google Earth API, without the need to generate `static` terrain maps from raw DEM data... a **GE** dependent way...

As discussed before, maybe there is a way to setup a DEM http server, that can also generate colored height maps on the fly, instead of using `static` data... a **non-GE** dependent way...

While I have nothing wrong with **GE** being in everything, I certainly do prefer **independence** ;=))

See #5 for some small additions, including a **GE** XML file...

**Comment by theo-armour** [comment]
@geoffmcl 

> >  I can see maybe the terrain could come from the Google Earth API,

I avoid Google Earth as much as possible. It feels like a product designed by civil servants for programming by civil servants - ie make it as slow, cumbersome and as obtuse as possible so as to create more jobs. There's nothing wrong with that, it's just not my style.

I can and do put up with the [Google Maps API](https://developers.google.com/maps/)

There appears to be little or no connection between Google Maps and Google Earth.

The [Elevation Service](https://developers.google.com/maps/documentation/javascript/elevation) I am using is part of Google Maps.

Currently I am gathering DEM data from the elevation service - for specific locations on an as needed basis - and then saving it to disk for ongoing use.  A new way of working for me. More later.

> > While I have nothing wrong with GE being in everything, I certainly do prefer independence ;=))

Agreed.

In this case, the idea is to use the Elevation Service once and be independent thereafter.
